// 受け答え問題のデータ。q = 相手（係員・店員・キャストなど）に言われる一言、a = 自分の返し。
// c はジャンル番号（data.js の CATEGORIES と同じ）。手で追加・修正してよい。
const DIALOGS = [
  // 0 空港・出発
  {c:0, q:"Could you pull up your boarding pass, please?", qja:"搭乗券を表示していただけますか？", a:"Sure, here you are.", aja:"はい、どうぞ。"},
  {c:0, q:"Which airline are you flying with?", qja:"どの航空会社ですか？", a:"We're flying with Japan Airlines.", aja:"日本航空です。"},
  {c:0, q:"Passport and boarding pass, please.", qja:"パスポートと搭乗券をお願いします。", a:"Here you are.", aja:"はい、どうぞ。"},
  {c:0, q:"Your bag is two pounds overweight.", qja:"お荷物が2ポンド超過しています。", a:"Can I move some things to my carry-on?", aja:"機内持ち込みの方に少し移してもいいですか？"},
  {c:0, q:"Would you like an aisle or a window seat?", qja:"通路側と窓側、どちらがよろしいですか？", a:"An aisle seat, please.", aja:"通路側でお願いします。"},
  {c:0, q:"Please take off your shoes and belt.", qja:"靴とベルトを外してください。", a:"Got it. Do I need to take out my laptop?", aja:"分かりました。ノートパソコンも出しますか？"},
  {c:0, q:"Do you have any liquids in your bag?", qja:"カバンに液体物は入っていますか？", a:"Just a small bottle of water.", aja:"小さい水のボトルだけです。"},
  {c:0, q:"How many bags are you checking today?", qja:"本日お預けの荷物はいくつですか？", a:"Two checked bags.", aja:"預け荷物は2つです。"},
  {c:0, q:"Your gate changed to B24.", qja:"搭乗口がB24に変更になりました。", a:"Thanks. Is it far from here?", aja:"ありがとう。ここから遠いですか？"},
  {c:0, q:"Boarding begins in twenty minutes.", qja:"搭乗開始は20分後です。", a:"Okay. Is there a restroom near the gate?", aja:"分かりました。搭乗口の近くにトイレはありますか？"},
  // 1 機内
  {c:1, q:"Would you like chicken or pasta?", qja:"チキンとパスタ、どちらになさいますか？", a:"I would like the chicken, please.", aja:"チキンをお願いします。"},
  {c:1, q:"Anything else I can get you?", qja:"ほかに何かお持ちしましょうか？", a:"Could I get a blanket, please?", aja:"ブランケットをもらえますか？"},
  {c:1, q:"Anything to drink?", qja:"お飲み物はいかがですか？", a:"Apple juice, no ice, please.", aja:"りんごジュースを氷なしでお願いします。"},
  {c:1, q:"Excuse me, is this seat taken?", qja:"すみません、この席は空いていますか？", a:"No, go ahead.", aja:"いいえ、どうぞ。"},
  {c:1, q:"Do you mind if I recline my seat?", qja:"席を倒してもいいですか？", a:"Not at all, go ahead.", aja:"全然かまいません、どうぞ。"},
  {c:1, q:"Sorry, we've run out of the pasta.", qja:"申し訳ありません、パスタは終わってしまいました。", a:"That's fine. I'll have the chicken, then.", aja:"大丈夫です。ではチキンにします。"},
  {c:1, q:"Please keep your seat belt fastened.", qja:"シートベルトを締めたままでいてください。", a:"Okay, thank you.", aja:"はい、ありがとう。"},
  {c:1, q:"Could you put your tray table up?", qja:"テーブルを戻していただけますか？", a:"Sure, sorry about that.", aja:"はい、すみません。"},
  {c:1, q:"We'll be landing in about thirty minutes.", qja:"あと30分ほどで着陸します。", a:"Thank you. Do we need to fill out a customs form?", aja:"ありがとう。税関の書類は書く必要がありますか？"},
  // 2 入国審査・税関・到着
  {c:2, q:"What's the purpose of your visit?", qja:"渡航の目的は何ですか？", a:"Sightseeing. We're here on vacation.", aja:"観光です。休暇で来ました。"},
  {c:2, q:"How long are you staying?", qja:"どのくらい滞在しますか？", a:"Ten days.", aja:"10日間です。"},
  {c:2, q:"Where are you staying?", qja:"どこに滞在しますか？", a:"At a hotel near Disney World.", aja:"ディズニーワールド近くのホテルです。"},
  {c:2, q:"Are you traveling alone?", qja:"お一人での旅行ですか？", a:"No, I'm with my wife.", aja:"いいえ、妻と一緒です。"},
  {c:2, q:"Do you have anything to declare?", qja:"申告するものはありますか？", a:"No, I have nothing to declare.", aja:"いいえ、申告するものはありません。"},
  {c:2, q:"Is this your first time in the States?", qja:"アメリカは初めてですか？", a:"Yes, it's our first time.", aja:"はい、初めてです。"},
  {c:2, q:"Please put four fingers on the scanner.", qja:"4本の指をスキャナーに置いてください。", a:"Like this?", aja:"こうですか？"},
  {c:2, q:"Are you bringing in any food?", qja:"食品は持ち込んでいますか？", a:"Just some snacks from Japan.", aja:"日本のお菓子が少しだけです。"},
  {c:2, q:"All right, you're good to go.", qja:"はい、もう行って大丈夫です。", a:"Thank you. Have a good one.", aja:"ありがとう。よい一日を。"},
  {c:2, q:"Which flight did you come in on?", qja:"どの便で到着しましたか？", a:"Flight 168 from Osaka.", aja:"大阪からの168便です。"},
  // 3 移動
  {c:3, q:"Are you Pei? Where are you headed today?", qja:"ペイさんですか？今日はどちらへ？", a:"Yes. To the Grand Hotel, please.", aja:"はい。グランドホテルまでお願いします。"},
  {c:3, q:"Traffic is bad this time of day.", qja:"この時間帯は渋滞します。", a:"No worries. Take your time.", aja:"大丈夫です。ゆっくりでいいですよ。"},
  {c:3, q:"May I see your driver's license?", qja:"運転免許証を見せていただけますか？", a:"Sure. I also have an international permit.", aja:"はい。国際免許証もあります。"},
  {c:3, q:"Please return it with a full tank.", qja:"満タンにして返却してください。", a:"Got it. Is there a gas station near the airport?", aja:"分かりました。空港の近くにガソリンスタンドはありますか？"},
  {c:3, q:"Where do you want to get off?", qja:"どこで降りますか？", a:"At the Magic Kingdom stop, please.", aja:"マジックキングダムの停留所でお願いします。"},
  {c:3, q:"It's a big blue sign — you can't miss it.", qja:"大きな青い看板なのですぐ分かりますよ。", a:"Great, thank you so much.", aja:"よかった、本当にありがとう。"},
  {c:3, q:"Go straight for two blocks and turn left at the light.", qja:"2ブロックまっすぐ行って、信号を左です。", a:"Straight, then left at the light. Got it.", aja:"まっすぐ行って信号を左ですね。分かりました。"},
  {c:3, q:"That'll be twenty-two dollars.", qja:"22ドルです。", a:"Here you go. Keep the change.", aja:"どうぞ。おつりは取っておいてください。"},
  {c:3, q:"Would you like to add insurance to the rental?", qja:"レンタルに保険を追加しますか？", a:"Does the rate already include basic insurance?", aja:"料金に基本の保険はもう含まれていますか？"},
  {c:3, q:"The shuttle runs every twenty minutes.", qja:"シャトルは20分おきに来ます。", a:"Thanks. Where do we get on?", aja:"ありがとう。どこから乗ればいいですか？"},
  // 4 ホテル・リゾート
  {c:4, q:"Good morning! Are you checking in?", qja:"おはようございます。チェックインですか？", a:"Yes. We have a reservation under Asai.", aja:"はい。浅井の名前で予約しています。"},
  {c:4, q:"What's your room number?", qja:"お部屋番号は？", a:"It's 612.", aja:"612号室です。"},
  {c:4, q:"Would you like a wake-up call?", qja:"モーニングコールはご入用ですか？", a:"Yes, at six, please.", aja:"はい、6時にお願いします。"},
  {c:4, q:"Here's your key. Enjoy your stay!", qja:"鍵をどうぞ。良いご滞在を。", a:"Thank you!", aja:"ありがとう！"},
  {c:4, q:"How would you like to pay for the deposit?", qja:"保証金のお支払いはどうなさいますか？", a:"By credit card, please.", aja:"クレジットカードでお願いします。"},
  {c:4, q:"Is there anything else I can help you with?", qja:"ほかに何かお手伝いできることは？", a:"Yes. What's the Wi-Fi password?", aja:"はい。Wi-Fiのパスワードは何ですか？"},
  {c:4, q:"Housekeeping. May I come in?", qja:"清掃です。入ってもよろしいですか？", a:"Could you come back after noon?", aja:"正午以降に来てもらえますか？"},
  {c:4, q:"Checkout is at eleven.", qja:"チェックアウトは11時です。", a:"Can we request a late checkout?", aja:"レイトチェックアウトをお願いできますか？"},
  {c:4, q:"Breakfast is a buffet on the second floor.", qja:"朝食は2階のビュッフェです。", a:"Is breakfast included?", aja:"朝食は含まれていますか？"},
  {c:4, q:"I'm sorry, the room isn't ready yet.", qja:"申し訳ありません、お部屋の準備がまだできていません。", a:"That's fine. Could you hold our luggage until three?", aja:"大丈夫です。3時まで荷物を預かってもらえますか？"},
  {c:4, q:"Is everything okay with your room?", qja:"お部屋に問題はありませんか？", a:"Actually, the air conditioning isn't working.", aja:"実は、冷房が効いていません。"},
  // 5 レストラン・カフェ
  {c:5, q:"How many in your party?", qja:"何名様ですか？", a:"A table for two, please.", aja:"2名でお願いします。"},
  {c:5, q:"Do you have a reservation?", qja:"ご予約はありますか？", a:"No. Do you take walk-ins?", aja:"いいえ。予約なしでも入れますか？"},
  {c:5, q:"Are you ready to order?", qja:"ご注文はお決まりですか？", a:"Yes. I'll have the chicken entree.", aja:"はい。メインはチキンにします。"},
  {c:5, q:"How would you like your steak?", qja:"ステーキの焼き加減はいかがしますか？", a:"Medium rare, please.", aja:"ミディアムレアでお願いします。"},
  {c:5, q:"What can I get you to drink?", qja:"お飲み物は何になさいますか？", a:"Just ice water for now, please.", aja:"とりあえずお冷やをお願いします。"},
  {c:5, q:"Would you like fries or a salad with that?", qja:"付け合わせはポテトとサラダ、どちらにしますか？", a:"A side salad, please.", aja:"サイドサラダでお願いします。"},
  {c:5, q:"How's everything tasting?", qja:"お味はいかがですか？", a:"It's delicious. Thank you.", aja:"とてもおいしいです、ありがとう。"},
  {c:5, q:"Can I get a name for the order?", qja:"ご注文のお名前をいただけますか？", a:"Pei. P-E-I.", aja:"ペイです。P、E、I。"},
  {c:5, q:"For here or to go?", qja:"店内ですか、お持ち帰りですか？", a:"To go, please.", aja:"持ち帰りでお願いします。"},
  {c:5, q:"Would you like a to-go box?", qja:"お持ち帰り用の箱はご入用ですか？", a:"Yes, please. We'll take the leftovers with us.", aja:"はい。残りは持ち帰ります。"},
  {c:5, q:"Can I get you anything else?", qja:"ほかに何かお持ちしましょうか？", a:"Just the check, please.", aja:"お会計だけお願いします。"},
  {c:5, q:"The wait is about thirty minutes.", qja:"待ち時間は30分ほどです。", a:"That's fine. Can you put us on the wait list?", aja:"大丈夫です。ウェイティングリストに入れてもらえますか？"},
  {c:5, q:"Does anyone have any allergies?", qja:"アレルギーのある方はいらっしゃいますか？", a:"My wife has a nut allergy.", aja:"妻はナッツアレルギーです。"},
  {c:5, q:"What size would you like?", qja:"サイズはどうなさいますか？", a:"A medium, please.", aja:"Mサイズでお願いします。"},
  {c:5, q:"Will this be on one check or separate?", qja:"お会計は一緒ですか、別々ですか？", a:"One check is fine.", aja:"一緒で大丈夫です。"},
  // 6 買い物・支払い
  {c:6, q:"Are you finding everything okay?", qja:"お探しのものは見つかりましたか？", a:"Yes, thanks. I'm just looking.", aja:"はい、ありがとう。見ているだけです。"},
  {c:6, q:"Can I help you find something?", qja:"何かお探しですか？", a:"Do you have this hoodie in navy?", aja:"このパーカーの紺色はありますか？"},
  {c:6, q:"That's nineteen ninety-nine plus tax.", qja:"19ドル99セント、税別です。", a:"Okay. Do you take credit cards?", aja:"分かりました。クレジットカードは使えますか？"},
  {c:6, q:"Would you like a bag?", qja:"袋はご入用ですか？", a:"Yes, please.", aja:"はい、お願いします。"},
  {c:6, q:"Cash or card?", qja:"現金ですか、カードですか？", a:"Card, please.", aja:"カードでお願いします。"},
  {c:6, q:"Could you sign here, please?", qja:"ここにサインをお願いします。", a:"Sure.", aja:"はい。"},
  {c:6, q:"Sorry, that one's sold out.", qja:"申し訳ありません、それは売り切れです。", a:"Do you carry it in another store?", aja:"他の店舗にはありますか？"},
  {c:6, q:"Do you need a receipt?", qja:"レシートはご入用ですか？", a:"Yes, please. I might return it.", aja:"はい。返品するかもしれないので。"},
  {c:6, q:"Do you want to try it on?", qja:"試着されますか？", a:"Yes. Where's the fitting room?", aja:"はい。試着室はどこですか？"},
  {c:6, q:"Is that everything for you today?", qja:"本日はこちらで全部ですか？", a:"Yes, that's it. Thank you.", aja:"はい、これで全部です。ありがとう。"},
  {c:6, q:"Everything here is twenty percent off.", qja:"こちらは全品20%引きです。", a:"Nice. I'll take it.", aja:"いいですね。これにします。"},
  // 7 テーマパーク
  {c:7, q:"Can I see your park ticket?", qja:"パークチケットを見せていただけますか？", a:"Sure, it's on the app.", aja:"はい、アプリに入っています。"},
  {c:7, q:"Keep your wristband on all day.", qja:"リストバンドは一日中着けたままにしてください。", a:"Got it, thanks.", aja:"分かりました、ありがとう。"},
  {c:7, q:"Your return time is at two thirty.", qja:"戻ってくる時間は2時半です。", a:"Great, we'll be back then.", aja:"了解です、その時間に戻ります。"},
  {c:7, q:"The ride is temporarily closed.", qja:"このライドは一時的に運休しています。", a:"Do you know when it will reopen?", aja:"いつ再開するか分かりますか？"},
  {c:7, q:"Would you like to try the single rider line? It's shorter.", qja:"シングルライダーの列にしますか？そちらの方が短いです。", a:"Sure, we'll do that.", aja:"はい、そうします。"},
  {c:7, q:"Would you like a photo?", qja:"お写真はいかがですか？", a:"Yes, please. Could you take one more?", aja:"はい、お願いします。もう一枚撮ってもらえますか？"},
  {c:7, q:"You'll need a hand stamp to come back.", qja:"戻るには手にスタンプが必要です。", a:"Okay, could I get one, please?", aja:"分かりました、押してもらえますか？"},
  {c:7, q:"How many are in your group?", qja:"何名様のグループですか？", a:"Two.", aja:"2人です。"},
  {c:7, q:"The show is cancelled because of the rain.", qja:"雨のためショーは中止です。", a:"That's too bad. Is there a later showtime?", aja:"残念です。あとの回はありますか？"},
  {c:7, q:"Pick up your order at window three.", qja:"3番窓口でお受け取りください。", a:"Window three. Got it.", aja:"3番窓口ですね。分かりました。"},
  {c:7, q:"How was the ride?", qja:"ライドはどうでしたか？", a:"It was amazing. Worth the wait.", aja:"最高でした。並んだ甲斐がありました。"},
  {c:7, q:"Do you need a map of the park?", qja:"パークマップは必要ですか？", a:"Yes, please.", aja:"はい、お願いします。"},
  {c:7, q:"Lockers are required for this ride.", qja:"このライドではロッカーの利用が必須です。", a:"Okay. Where are the lockers?", aja:"分かりました。ロッカーはどこですか？"},
  // 8 体調・薬・トラブル
  {c:8, q:"What seems to be the problem?", qja:"どうされましたか？", a:"My wife isn't feeling well. She feels dizzy.", aja:"妻の体調が良くありません。めまいがするそうです。"},
  {c:8, q:"Do you have any allergies to medication?", qja:"薬のアレルギーはありますか？", a:"No, none.", aja:"いいえ、ありません。"},
  {c:8, q:"Take two every six hours.", qja:"6時間おきに2錠飲んでください。", a:"With food, or is it okay on an empty stomach?", aja:"食後ですか、空腹でも大丈夫ですか？"},
  {c:8, q:"Do you have travel insurance?", qja:"旅行保険には入っていますか？", a:"Yes, we do. Here's the card.", aja:"はい、入っています。こちらがカードです。"},
  {c:8, q:"When did you lose it?", qja:"いつなくしましたか？", a:"This afternoon, somewhere in the park.", aja:"今日の午後、パークのどこかです。"},
  {c:8, q:"Can you describe the bag?", qja:"カバンの特徴を教えてください。", a:"It's a small black backpack.", aja:"小さい黒のリュックです。"},
  {c:8, q:"Is there anything else wrong with the room?", qja:"お部屋にほかに問題はありますか？", a:"Yes, the safe is broken.", aja:"はい、金庫が壊れています。"},
  {c:8, q:"I'm sorry about the mix-up.", qja:"手違いがあり申し訳ありません。", a:"No worries. Could we change rooms, please?", aja:"気にしないでください。部屋を替えてもらえますか？"},
  {c:8, q:"Do you need me to call an ambulance?", qja:"救急車を呼びましょうか？", a:"No, I think we just need to rest.", aja:"いいえ、少し休めば大丈夫だと思います。"},
  // 9 お金・通信・手続き
  {c:9, q:"Do you have your confirmation number?", qja:"予約確認番号はお持ちですか？", a:"Yes, it's on my phone.", aja:"はい、スマホに入っています。"},
  {c:9, q:"Would you like to pay in advance?", qja:"前払いになさいますか？", a:"Is there free cancellation if we do?", aja:"その場合、無料キャンセルはできますか？"},
  {c:9, q:"How would you like your cash?", qja:"現金はどのように（紙幣の種類）しますか？", a:"Some small bills, please.", aja:"小さい紙幣でお願いします。"},
  {c:9, q:"Just scan the QR code on the table.", qja:"テーブルのQRコードを読み取ってください。", a:"Got it. Can I sign in as a guest?", aja:"分かりました。ゲストでログインできますか？"},
  {c:9, q:"Do you need an adapter?", qja:"変換プラグは必要ですか？", a:"No, I brought one. Where's the outlet?", aja:"いいえ、持ってきました。コンセントはどこですか？"},
  {c:9, q:"There's a three-dollar fee for this ATM.", qja:"このATMは手数料が3ドルかかります。", a:"That's fine. I need to withdraw some cash.", aja:"大丈夫です。現金を引き出したいので。"},
  // 10 天気・時間・数量
  {c:10, q:"The forecast says rain in the afternoon.", qja:"予報では午後は雨です。", a:"Should we bring an umbrella?", aja:"傘を持っていったほうがいいですか？"},
  {c:10, q:"What time should we meet?", qja:"何時に待ち合わせましょうか？", a:"Let's meet at six o'clock in the lobby.", aja:"6時にロビーで待ち合わせよう。"},
  {c:10, q:"They close the ride during a thunderstorm.", qja:"雷雨のときはライドを止めます。", a:"How long does it usually last?", aja:"だいたいどのくらい続きますか？"},
  {c:10, q:"Are you in a hurry?", qja:"お急ぎですか？", a:"Sorry, we're running a little late.", aja:"すみません、少し遅れています。"},
  {c:10, q:"It cools down after sunset.", qja:"日が沈むと涼しくなります。", a:"Good. Let's come back this evening, then.", aja:"よかった。じゃあ夕方にまた来よう。"},
  {c:10, q:"What time does it start?", qja:"何時に始まりますか？", a:"At half past seven.", aja:"7時半です。"},
  // 11 あいさつ・受け答え
  {c:11, q:"Hi there! How are you today?", qja:"こんにちは。今日はご機嫌いかがですか？", a:"I'm doing well, thanks. And you?", aja:"元気です、ありがとう。あなたは？"},
  {c:11, q:"Nice to meet you. I'm Sam.", qja:"はじめまして。サムです。", a:"Nice to meet you. I'm Pei.", aja:"はじめまして。ペイです。"},
  {c:11, q:"You're welcome! Have a good one.", qja:"どういたしまして。良い一日を。", a:"Thanks! You too.", aja:"ありがとう。あなたも。"},
  {c:11, q:"Take care, and enjoy your trip!", qja:"気をつけて、良い旅を。", a:"Thank you for everything.", aja:"いろいろありがとう。"},
  {c:11, q:"Do you need anything else?", qja:"ほかに何か必要ですか？", a:"No thanks, we're all set.", aja:"いいえ、大丈夫です。"},
  {c:11, q:"Where are you from?", qja:"どちらから来ましたか？", a:"We're from Osaka, Japan.", aja:"日本の大阪から来ました。"},
  {c:11, q:"After you.", qja:"お先にどうぞ。", a:"Oh, thank you.", aja:"あ、ありがとう。"},
  {c:11, q:"Pardon me? Could you repeat that?", qja:"すみません、もう一度お願いできますか？", a:"Sure. A table for two, please.", aja:"はい。2名でお願いします。"},
  {c:11, q:"Which one do you want?", qja:"どれにしますか？", a:"Let me see... I'll take this one.", aja:"ええと…これにします。"},
  {c:11, q:"Sorry, we don't have that today.", qja:"申し訳ありません、今日はそれがありません。", a:"No worries. What do you recommend instead?", aja:"気にしないで。代わりのおすすめは何ですか？"},
  // 12 感想・気持ち
  {c:12, q:"How was the show?", qja:"ショーはどうでしたか？", a:"That show was amazing.", aja:"あのショーは素晴らしかったです。"},
  {c:12, q:"Are you having fun?", qja:"楽しんでいますか？", a:"Yes! This is a dream come true.", aja:"はい！夢がかないました。"},
  {c:12, q:"Was it worth the wait?", qja:"待った甲斐はありましたか？", a:"Definitely. It was better than I expected.", aja:"もちろん。思っていたより良かったです。"},
  {c:12, q:"Are you tired?", qja:"疲れましたか？", a:"A little, but happy.", aja:"少し。でも満足です。"},
  {c:12, q:"How's your trip going so far?", qja:"ここまで旅はどうですか？", a:"So far, this is the best day.", aja:"今のところ、今日が一番いい日です。"},
  {c:12, q:"Did you like the fireworks?", qja:"花火は気に入りましたか？", a:"Yes, it was an unforgettable night.", aja:"はい、忘れられない夜でした。"},
];
